name: Puppet Lint IaC

on: [push]

jobs:
  lint:
    name: puppet-lint-iac
    steps:
      - uses: action/checkout@v2
      - uses: TQRG/puppet-lint-security-iac/.github/workflows/ci.yml@v2.0.0
        with:
          working-directory: ./examples/
